### ISSUE TITLE
iwgtk is killed when restarting iwd or when the interface (phy) is disabled

### ISSUE THREAD

**Issue by gothmog123** [J-Lentz/iwgtk#13]
Do you think you it would be possible to have iwd remain running in these situations?

**Comment by J-Lentz** [comment]
This has been fixed in commits 0cf9eefb1b2e42f9a99a8b4289b741570f182e00, adfe7cb57e170c811e03a691603a2194b133c540, and 6f335e887cbe60265f92bf8f5c4043464f68781c. Now, iwgtk will run idly in the background when iwd is down.
