### ISSUE TITLE
Indicator icons not showing up

### ISSUE THREAD

**Issue by macxcool** [J-Lentz/iwgtk#15]
I'm creating an AUR package for Archlinux for this (it's nice, btw) and it compiles and runs just fine, but:
1. I don't see a tray icon
2. When I run 'iwgtk -i' there are no indicators (I assume you mean there should be something in the tray?)

I'm running i3wm on xorg, so I do have a notification area (system tray).

**Comment by J-Lentz** [comment]
Does i3bar's system tray support the StatusNotifierItem API, or only XEmbed? iwgtk uses StatusNotifierItem, so if your tray only supports XEmbed, you'll need something along the lines of the following: https://git.sr.ht/~steef/snixembed

As a side note, I maintain an AUR package for iwgtk: https://aur.archlinux.org/packages/iwgtk/

**Comment by macxcool** [comment]
I guess the XEmbed thing must be it. I didn't realize.
As for the AUR package. I missed it because I search for iwd, LOL. Maybe you could consider putting iwd somewhere in the description for greater visibility?
Anyway. Thanks for the response and for a nice little utility. I was kinda looking for something like this. I ditched NetworkManager quite awhile ago for iwd. iwctl is pretty nice, but I decided to go and see if there was a gui around the other day and found this.

-- Mark Coolen
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Jun 25, 2021, 8:39 PM by ***@***.***:

**Comment by J-Lentz** [comment]
Thanks for the suggestion. I'll change the AUR package description on the next update so that people searching for "iwd" can find it more easily.

I was in the same boat when I began working on this: I found that standalone iwd worked nicely on my laptop, but that it lacked a graphical front-end.
