### ISSUE TITLE
Tray icon does not display on i3wm (i3status tray)

### ISSUE THREAD

**Issue by grepsedawk** [J-Lentz/iwgtk#19]
When running  `iwgtk -i`, no tray icon appears.
I do have other tray icons like bluetooth and pulse applets running fine, so it's not an overall i3 tray issue

I can provide any other information, and I'm even willing to hop on a call to help debug this if you'd like

**Comment by J-Lentz** [comment]
Hi,

iwgtk uses the StatusNotifierItem tray icon API. I believe i3bar only supports the older XEmbed API, which means you'll need a StatusNotifierItem -> XEmbed compatibility layer such as the following:

https://git.sr.ht/~steef/snixembed

Let me know if it works for you. I expect you're not the only one experiencing this problem, so putting a link to the above project into the README may be worthwhile.

**Comment by grepsedawk** [comment]
Yep that did the trick!
