### ISSUE TITLE
systemd - could this be mentioned in the main README?

### ISSUE THREAD

**Issue by rubyFeedback** [J-Lentz/iwgtk#2]
Hi there,

I found this on reddit, and managed to compile iwgtk. The GUI told me that there is no
iwd daemon running.

I tried to compile iwd from here:

https://git.kernel.org/pub/scm/network/wireless/iwd.git/

Unfortunately it seems to depend on systemd; tried --disable-systemd to no avail.

If this is correct this means that iwgtk also requires systemd implicitely (since iwd 
needs it). Could you perhaps mention this if you intend to update the main
README? (And perhaps also add a screenshot or two to the main README if
you find the time to update that.)

Clearly mentioning the systemd dependency may help, as folks who avoid systemd
don't run into that frustrating "systemd-only" part that iwd requires (I tried --disable-systemd
but that did not help. May be that this is due to dbus, or perhaps my system is messed
up due to unrelated errors made)

checking D-Bus bus services directory... /usr/share/dbus-1/system-services
checking systemd unit directory... Package systemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `systemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'systemd' found

**Comment by J-Lentz** [comment]
Hello,

systemd is not required to compile and run iwd. It looks like the ./configure flag you want to use is: --disable-systemd-service. With that said, most distros should offer an iwd package - if available, this will make your life easier in the short-term and in the long-term.

A screenshot in the README.md file is a good idea.
