### ISSUE TITLE
known networks, can't get back to main view

### ISSUE THREAD

**Issue by RO5CH** [J-Lentz/iwgtk#23]
hey,
just found a quick problem. if you click known networks,
there is no way to get back to the main network list. there is no back button.
you have to click on quit & reopen iwgtk.

**Comment by J-Lentz** [comment]
Do you have a button in the upper-lefthand corner labeled "wlan0", or whatever the interface is called on your system?

**Comment by RO5CH** [comment]
oh yes you are right. it was not that clear. 
thanks, i guess we can close this issue.
