### ISSUE TITLE
Indicator click issue

### ISSUE THREAD

**Issue by notgood** [J-Lentz/iwgtk#25]
Latest iwgtk from AUR.

Clicking on iwgtk indicator opens main window, another click closes it, but only if main window is currently focused.

If window is not focused, minimized, etc. then indicator click opens new duplicate, which isn't logical and is kind of confusing.

**Comment by J-Lentz** [comment]
This behavior was changed on Sep. 16, 2020, and the most recent release (0.4) was made... on Sep. 13, 2020. So I'd say a 0.5 release is overdue.

**Comment by notgood** [comment]
Nice, waiting for 0.5 release then.

Not sure if its related, but turning off WiFi using phy or power toggle makes indicator icon disapper. Closing window in this state quits application, instead of minimizing to tray. Running "iwgtk -i" with powered down WiFi also makes application insta quit.

**Comment by J-Lentz** [comment]
I'm working on a complete overhaul of the indicator icon UX for 0.5, which should fix that issue among other problems. My plan is to release 0.5 after the next iwd release, since it depends on some very recent changes to the behavior of iwd's SignalLevelAgent API.
