### ISSUE TITLE
Icons don't display correctly unless adwaita is set as icon theme in kde

### ISSUE THREAD

**Issue by danielkermode** [J-Lentz/iwgtk#27]
![ksnip_20220618-200120](https://user-images.githubusercontent.com/10554809/174428769-0d1f09c2-db14-4160-a2cc-e2e213635d89.png)

Icons don't display correctly unless icon theme is set to adwaita in icon settings. The rest of the app works correctly either way. Is this intended behaviour?

**Comment by J-Lentz** [comment]
Nope, it's a bug. Are you using Breeze icons? I'm seeing two possible issues:
* Breeze doesn't provide network-wireless-offline, network-wireless-disabled, or network-wireless-hardware-disabled icons.
* Breeze doesn't provide -symbolic versions of its icons.

A couple questions:
* Does the tray icon look correct when you're connected to a network?
* If not, does it change color when you connect/disconnect?

**Comment by danielkermode** [comment]
Yes, using breeze icons. I tested with adwaita and candy-icons and both work correctly so it's probably a breeze thing (haven't tested others). None of the correct icons are displayed, even when connected to a network or connecting/disconnecting, just the error icon in the screenshot above.

**Comment by henning-schild** [comment]
same here on gentoo linux, it seems there are no -symbolic versions of the icons

``` $ find /usr/share/icons/breeze/ -name network-wireless* | grep -v 16 | grep -v 22
/usr/share/icons/breeze/status/24/network-wireless-connected-100.svg
/usr/share/icons/breeze/status/24/network-wireless-connected-50.svg
/usr/share/icons/breeze/status/24/network-wireless-signal-ok.svg
/usr/share/icons/breeze/status/24/network-wireless-connected-00.svg
/usr/share/icons/breeze/status/24/network-wireless-signal-good.svg
/usr/share/icons/breeze/status/24/network-wireless-connected-75.svg
/usr/share/icons/breeze/status/24/network-wireless-signal-none.svg
/usr/share/icons/breeze/status/24/network-wireless-connected-25.svg
/usr/share/icons/breeze/status/24/network-wireless-disconnected.svg
/usr/share/icons/breeze/status/24/network-wireless-acquiring.svg
/usr/share/icons/breeze/status/24/network-wireless-signal-excellent.svg
/usr/share/icons/breeze/status/24/network-wireless-signal-weak.svg
/usr/share/icons/breeze/devices/24/network-wireless.svg
/usr/share/icons/breeze/devices/24/network-wireless-hotspot.svg
/usr/share/icons/breeze/devices/symbolic/network-wireless-symbolic.svg
```

so no "-symbolic"

no "network-wireless-offline", no "network-wireless-disabled", no "network-wireless-hardware-disabled"

**Comment by henning-schild** [comment]
likely introduced with https://github.com/J-Lentz/iwgtk/pull/11 https://github.com/J-Lentz/iwgtk/commit/077b61d61b585685ce3e70875595b8c1e0164480

**Comment by henning-schild** [comment]
@JoveYu

**Comment by JoveYu** [comment]
iwgtk using GTK toolkit, any icons theme made for GTK is all right, but breeze icons is for KDE, lost many icons for GTK apps.

**Comment by JoveYu** [comment]
this project extend breeze icon theme to GTK

https://github.com/kuroehanako/breeze-extended

**Comment by J-Lentz** [comment]
Perhaps the right behavior would be to check that all icons used by the app are available on startup, and if any are missing, print a warning and override the theme to Adwaita.

**Comment by henning-schild** [comment]
cool! if there was a release i would make sure to bring this into gentoo

**Comment by henning-schild** [comment]
just picking that one patch the tray icon will still have no icon, but in the application things look good

**Comment by J-Lentz** [comment]
That's strange. The theme override applies to scan result icons and to indicator icons, so both should be fixed. Does the theme override message get printed to stderr on startup?

**Comment by henning-schild** [comment]
taking to #30
