### ISSUE TITLE
Undefined reference to 'gtk_symbolic_paintable_snapshot_symbolic'

### ISSUE THREAD

**Issue by Lppsoeht** [J-Lentz/iwgtk#28]
I have the needed packages installed
Full sterr:
`/usr/bin/ld: icon.o: in function
"symbolic_icon_get_snapshot":
icon.c: (.text+@xed): undefined reference to 'GTK_SYMBOLIC_PAINTABLE'
/usr/bin/ld: icon.c:(.text+@xlld): undefined reference to
'gtk_symbolic_paintable_snapshot_symbolic'
collect2: error: ld returned 1 exit status
make: *** [Makefile:26: iwgtk] Error 1`

Uname -a:
`Linux fedora-34 5.10.90-l.fc32.x86_64 #1 SMP Thu Jan 13 20:46:58 CET 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by J-Lentz** [comment]
1) What version of gtk4 do you have installed?
2) Are you building the 0.6 release, or the current git repo?
3) Can you provide the full output from the `make` command?

Thank you.

**Comment by J-Lentz** [comment]
Also,

4) Can you provide the output of the following command: `pkg-config --libs gtk4` ?

**Comment by J-Lentz** [comment]
Ah, I see the problem. We use GTK4's SymbolicPaintable API, which was added to GTK 4.6. Fedora 34 presumably uses an older GTK4 release.

**Comment by Lppsoeht** [comment]
Gtk4 version:4.4.1
Make log:
`cc 'pkg-config --cflags gtk4'
-o iwgtk sni.o main.o window.o indicator.o dialog.o adapter.o device.o station.o wps.o diagnostic.o ap
adhoc.o utilities.o icon.o switch.o known_network.o network.o hidden.o agent.o
"pkg-config --libs gtk4°
/usr/bin/ld: icon.o: in function
"symbolic_icon_get_snapshot':
icon.c: (.text+oxed): undefined reference to
"GTK_SYMBOLIC_PAINTABLE
/usr/bin/ld: icon.c: (.text+@xlld): undefined reference to
"gtk_symbolic_paintable_snapshot_symbolic'
collect2: error: ld returned 1 exit status
make: *** [Makefile:26: iwgtk] Error 1
`

**Comment by J-Lentz** [comment]
Thanks, that confirms that the older GTK4 version is the problem. You'll either need to update to GTK 4.6, or use iwgtk 0.4 (which was the last release based on GTK3, before the GTK4 port).

I'll update the README to indicate that GTK 4.6 is required.
