### ISSUE TITLE
tray icon not working on breeze icon theme on KDE with latest master

### ISSUE THREAD

**Issue by henning-schild** [J-Lentz/iwgtk#30]
#27 did fix the in-app icons but the system tray icon still looks wrong

**Comment by henning-schild** [comment]
```
$ iwgtk -i
Icon theme 'breeze' is missing icon 'network-wireless-signal-excellent-symbolic': Overriding theme to Adwaita
```
but in the tray i just see an empty gap with f48e7c2c3b55a32e50be061a96bc809be8b4e284

**Comment by J-Lentz** [comment]
What version of iwd are you using?

**Comment by henning-schild** [comment]
1.27

**Comment by J-Lentz** [comment]
Ah, that's the problem. The indicator icon in station mode depends on recent changes made to iwd's SignalLevelAgent API, and therefore only works properly with iwd >=1.28.

**Comment by henning-schild** [comment]
ok cool, will do that!

**Comment by henning-schild** [comment]
https://github.com/gentoo/gentoo/pull/26170

**Comment by J-Lentz** [comment]
Great, thanks. I'll plan to make a 0.7 release shortly, since #27 probably affects a significant number of users on other distros as well.
