### ISSUE TITLE
Window position and size are no longer restored

### ISSUE THREAD

**Issue by funkymaster** [J-Lentz/iwgtk#33]
Hi,

thank you for a very useful app.
Unfortunately, the app no longer restores its previous position and size.
As far as I remember, this worked with v0.4.

Please repair.
Thx.

**Comment by J-Lentz** [comment]
Possibly related to the GTK3 -> GTK4 port. Window position should be controlled by your compositor or window manager. Can you confirm, using the current version of your compositor/WM, that position and size is preserved between iwgtk invocations in v0.4 but not in v0.5?

**Comment by funkymaster** [comment]
I'm on Xfce4.16 (xfwm) and moved directly from v0.4 to v0.7.
Yes, I can confirm, that position and size have been preserved in v0.4.
The application window was larger and that must be from a previous adjustment of mine.

**Comment by J-Lentz** [comment]
The default width has been made smaller in recent versions. Is horizontal scrolling due to long SSIDs the issue you're trying to resolve?

**Comment by funkymaster** [comment]
No, long SSID's are not the issue for me.

I just thought the app used to behave like [mousepad ](https://gitlab.xfce.org/apps/mousepad)does.
The default appearance of a window can be set to the middle of the screen with Xfce. That's what I have done in my DE and obviously how iwgtk behaves right now (v0.7). So, that's fine.
But additionalley every application can set and preserve the appearance position and size individually for itself.
And that's what I thought iwgtk would have done in v0.4.

**Comment by J-Lentz** [comment]
Looks like Mousepad stores and retrieves window dimensions via GLib's GSettings API. iwgtk doesn't use GSettings, but perhaps we could add width and height options to the configuration file so that the window size is customizable.

**Comment by J-Lentz** [comment]
Implemented in 816c29e016a1d5d503200a156ef1bedd9d99378c.

**Comment by funkymaster** [comment]
That's nice.
Thanks.
I'm just thinking if a check for misconfigurations would be good here? E.g. so that the window always has a minimum size and can never be larger than the screen resolution.

**Comment by J-Lentz** [comment]
Minimum window size has been implemented in a5b239c7a52396950522feb9c127d85026f1a2e0.
