### ISSUE TITLE
Systemtray has no icon

### ISSUE THREAD

**Issue by aalakhan19** [J-Lentz/iwgtk#35]
i have a empty space in my systemtray and i can click on it, but there is no icon. adwaita-icon-theme is installed.
I have a minimal arch install and use dwm. Am i missing something?

**Comment by J-Lentz** [comment]
Do icons appear in the available network list?

**Comment by J-Lentz** [comment]
Also, what are you using for your system tray? As far as I can see, dwm doesn't include a tray out of the box.

**Comment by aalakhan19** [comment]
yes when I click on it, everything has icons and looks like it is supposed to. I have the system tray patch for dwm applied

**Comment by aalakhan19** [comment]
ok I solved it, it was a dwm issue

**Comment by J-Lentz** [comment]
If you expect that other dwm users might benefit from your solution, then feel free to add it to README.md and submit a pull request. Otherwise, it seems that the issue is resolved.
