### ISSUE TITLE
release request... lol

### ISSUE THREAD

**Issue by gothmog123** [J-Lentz/iwgtk#4]
Sorry, could you do a release to include the new tray icon functionality? Or provide a git AUR package?

Thank you! Keep up the good work :+1:

**Comment by J-Lentz** [comment]
Will do once tray icon support is ready. Most likely this weekend. At this point, I've only committed some preliminary work to prepare for adding the tray icon.

**Comment by gothmog123** [comment]
thanks

**Comment by J-Lentz** [comment]
The 0.4 release now offers tray icons via the -i option.

**Comment by gothmog123** [comment]
Really appreciate it! Thanks for being so responsive
