### ISSUE TITLE
How to totally uninstall iwgtk

### ISSUE THREAD

**Issue by OrionRandD** [J-Lentz/iwgtk#42]
How do I totally uninstall (purge) iwgtk from my linux (debian) system?
Before installing it I could connect to hidden networks.
But, now "network-manager" complains about iwd not supporting hidden networks...

**Comment by J-Lentz** [comment]
Uninstalling iwgtk is a matter of removing all the files that were placed in your filesystem during the installation. These include:
* `$(prefix)/iwgtk` (the application binary itself)
* `$(prefix)/lib/systemd/user/iwgtk.service` (the systemd unit file)
* `$(prefix)/share/applications/iwgtk.desktop` (XDG desktop file)
* `$(prefix)/share/icons/hicolor/scalable/apps/iwgtk.svg` (the icon)
* `$(prefix)/share/man/man1/iwgtk.1.gz` (man page)
* `$(prefix)/share/man/man5/iwgtk.5.gz` (man page for config file)
* `/etc/iwgtk.conf` (config file)
* `/etc/xdg/autostart/iwgtk-indicator.desktop` (XDG autostart file)

With that said, removing iwgtk will most likely not resolve the problem you're having with NetworkManager. If you want to make NetworkManager use the `wpa_supplicant` back-end, then the following sequence of commands should be what you need (you might also need to adjust your NetworkManager configuration):
```
systemctl stop NetworkManager
systemctl disable --now iwd
systemctl enable --now wpa_supplicant
systemctl start NetworkManager
```

And with that said, `iwd` certainly does support connecting to hidden networks. You can do this through `iwgtk`, but I'm not sure whether or not NetworkManager's `iwd` backend supports this.
