### ISSUE TITLE
Valid D-Bus interface name

### ISSUE THREAD

**Issue by tinywrkb** [J-Lentz/iwgtk#5]
The interface name should be changed from `application.iwgtk` to something like `com.github.j_lentz.iwgtk`.

[D-Bus spec: Valid Names](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names)

> ...
> Interface names should start with the reversed DNS domain name of the author of the interface (in lower-case), like interface names in Java. It is conventional for the rest of the interface name to consist of words run together, with initial capital letters on all words ("CamelCase"). Several levels of hierarchy can be used. It is also a good idea to include the major version of the interface in the name, and increment it if incompatible changes are made; this way, a single object can implement several versions of an interface in parallel, if necessary.
> ...

**Comment by J-Lentz** [comment]
`com.github.j_lentz.iwgtk` is a bit ugly. Perhaps I'll register a domain so we can use `org.iwgtk` instead.

**Comment by tinywrkb** [comment]
Github pages can be used for an organization or user website, not only projects, so you can have an iwgtk organization with `iwgtk.github.io`website and the application id would be `io.github.iwgtk`. See [twitter.github.io](https://twitter.github.io/)

**Comment by J-Lentz** [comment]
I just registered `twosheds.org` to use for this and other open source projects down the road. My plan is to create a github pages website with the URL `iwgtk.twosheds.org`, and the application id will be `org.twosheds.iwgtk`.

**Comment by tinywrkb** [comment]
Nice! I see you already updated the icons filenames and the D-Bus name.  
Thanks!
