### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Muizzyranking** [J-Lentz/iwgtk#50]
I am unable to build this project because I am getting `meson.build:28:4: ERROR: Dependency "gtk4" not found, tried pkgconfig and cmake` but I already have gtk4 installed.
```
Last metadata expiration check: 0:08:59 ago on Sun 22 Dec 2024 05:10:28 PM WAT.
Package gtk4-4.14.5-1.fc40.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

What can I do?

**Comment by J-Lentz** [comment]
What distro are you using?

**Comment by Muizzyranking** [comment]
I am using fedora and I've been able to figure it out. Apparently, I needed to install gtk4-devel and libqrencode package is qrencode in fedora.
Thank you.
